[general]
working_directory = "Y:/git/"

# [terminal]
# shell = "wsl"

[window]
[window.dimensions]
columns = 100
lines = 40

[font]
size = 11
[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"
[font.offset]
x = 0
y = -1

[keyboard]
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

# Campbell colorscheme {{{
# (Windows 10/11 default)

# Default colors
[colors.primary]
background = '#0c0c0c'
foreground = '#cccccc'

# Normal colors
[colors.normal]
black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#13a10e'
yellow     = '#c19c00'
blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'

# Bright colors
[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'
# }}}
# vim: set foldmethod=marker:
